name: build-deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Stable with wasm
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown


      - name: Install wasm-bindgen
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-bindgen-cli
          version: latest
          use-tool-cache: true

      - name: Execute wasm-bindgen
        run: wasm-bindgen --out-dir ./out/ --target web ./target/wasm32-unknown-unknown/release/minesweeper-rs.wasm

      - name: Copy static web assets
        run: cp web-static/* out

      - name: Copy bevy assets
        run: cp -r assets out
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: out
